### ISSUE TITLE
No idea how to make a proper share button!

### ISSUE THREAD

**Issue by anjapatel** [anjapatel/namegenerator#3]
Tbf, I haven't looked into this <i>too</i> much yet because I wanted the rest of it to work first. :X So I"d say this is low priority until I take another stab!

**Comment by cr3ative** [comment]
So, this is specific to BuzzFeed. There are hooks in to which the app fires, for example. We have a sharing snippet which we use to normalise all this out - I'll copy and paste this in to the code shortly.
